version: "3"

services:
  neo4j: # test service for neo4j
    image: neo4j:enterprise
    hostname: neo4j
    container_name: neo4j_enterprise2
    ports:
      - "7474:7474"
      - "7687:7687"
    # Set paths for persistent data
    #volumes:
    #  - /path/data:/data
    #  - /path/import:/import
    #  - /path/logs:/logs
    #  - /path/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t4
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
