version: "3"

services:
  neo4j: # test service for neo4j
    image: neo4j:enterprise
    hostname: neo4j
    container_name: neo4j_enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
     - ./dockerdata:/data
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t4
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
